create table BITACORASISTEMA
(
	IIDBITACORASISTEMA BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	IIDUSUARIO INT NOT NULL FOREIGN KEY REFERENCES USUARIO,
	DESCRIPCIONBITACORA VARCHAR(200) NULL,
	FECHAACTIVIDAD DATETIME NULL
)