// <auto-generated />
using System;
using AdminFerreteria.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AdminFerreteria.Migrations
{
    [DbContext(typeof(BDFERRETERIAContext))]
    [Migration("20210531012210_creacion_sp")]
    partial class creacion_sp
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AdminFerreteria.Models.Bitacoraentrada", b =>
                {
                    b.Property<long>("Iidbotacorabodega")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IIDBOTACORABODEGA")
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Cantidad")
                        .HasColumnName("CANTIDAD")
                        .HasColumnType("bigint");

                    b.Property<int>("Iidbodega")
                        .HasColumnName("IIDBODEGA")
                        .HasColumnType("int");

                    b.Property<long>("Iidentrada")
                        .HasColumnName("IIDENTRADA")
                        .HasColumnType("bigint");

                    b.Property<long>("Iidproducto")
                        .HasColumnName("IIDPRODUCTO")
                        .HasColumnType("bigint");

                    b.Property<int>("Iidstock")
                        .HasColumnName("IIDSTOCK")
                        .HasColumnType("int");

                    b.Property<decimal>("Subcantidad")
                        .HasColumnName("SUBCANTIDAD")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("Iidbotacorabodega")
                        .HasName("PK__BITACORA__FC598AE78B4F2BC4");

                    b.HasIndex("Iidentrada");

                    b.ToTable("BITACORAENTRADA");
                });

            modelBuilder.Entity("AdminFerreteria.Models.Bitacorasistema", b =>
                {
                    b.Property<long>("Iidbitacorasistema")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IIDBITACORASISTEMA")
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcionbitacora")
                        .HasColumnName("DESCRIPCIONBITACORA")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<DateTime?>("Fechaactividad")
                        .HasColumnName("FECHAACTIVIDAD")
                        .HasColumnType("datetime");

                    b.Property<int>("Iidusuario")
                        .HasColumnName("IIDUSUARIO")
                        .HasColumnType("int");

                    b.HasKey("Iidbitacorasistema")
                        .HasName("PK__BITACORA__CE5281B56D4E1264");

                    b.HasIndex("Iidusuario");

                    b.ToTable("BITACORASISTEMA");
                });

            modelBuilder.Entity("AdminFerreteria.Models.Bodega", b =>
                {
                    b.Property<int>("Iidbodega")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IIDBODEGA")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bhabilitado")
                        .IsRequired()
                        .HasColumnName("BHABILITADO")
                        .HasColumnType("varchar(1)")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Nombrebodega")
                        .IsRequired()
                        .HasColumnName("NOMBREBODEGA")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.HasKey("Iidbodega")
                        .HasName("PK__BODEGA__ED00F28D0B40BCF5");

                    b.ToTable("BODEGA");
                });

            modelBuilder.Entity("AdminFerreteria.Models.Cliente", b =>
                {
                    b.Property<long>("Iidcliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IIDCLIENTE")
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bhabilitado")
                        .IsRequired()
                        .HasColumnName("BHABILITADO")
                        .HasColumnType("varchar(1)")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnName("DIRECCION")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<DateTime?>("Fechacreacion")
                        .HasColumnName("FECHACREACION")
                        .HasColumnType("date");

                    b.Property<string>("Giro")
                        .IsRequired()
                        .HasColumnName("GIRO")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<string>("Nit")
                        .IsRequired()
                        .HasColumnName("NIT")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("Nombrecompleto")
                        .IsRequired()
                        .HasColumnName("NOMBRECOMPLETO")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<string>("Registro")
                        .IsRequired()
                        .HasColumnName("REGISTRO")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.HasKey("Iidcliente")
                        .HasName("PK__CLIENTE__AF86765147BA2C40");

                    b.ToTable("CLIENTE");
                });

            modelBuilder.Entity("AdminFerreteria.Models.Configuracion", b =>
                {
                    b.Property<int>("Iidconfiguracion")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IIDCONFIGURACION")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Fincotizacion")
                        .HasColumnName("FINCOTIZACION")
                        .HasColumnType("bigint");

                    b.Property<long>("Fincreditofiscal")
                        .HasColumnName("FINCREDITOFISCAL")
                        .HasColumnType("bigint");

                    b.Property<long>("Finfactura")
                        .HasColumnName("FINFACTURA")
                        .HasColumnType("bigint");

                    b.Property<long>("Iniciocotizacion")
                        .HasColumnName("INICIOCOTIZACION")
                        .HasColumnType("bigint");

                    b.Property<long>("Iniciocreditofiscal")
                        .HasColumnName("INICIOCREDITOFISCAL")
                        .HasColumnType("bigint");

                    b.Property<long>("Iniciofactura")
                        .HasColumnName("INICIOFACTURA")
                        .HasColumnType("bigint");

                    b.Property<long>("Noactualcotizacion")
                        .HasColumnName("NOACTUALCOTIZACION")
                        .HasColumnType("bigint");

                    b.Property<long>("Noactualcreditofiscal")
                        .HasColumnName("NOACTUALCREDITOFISCAL")
                        .HasColumnType("bigint");

                    b.Property<long>("Noactualfactura")
                        .HasColumnName("NOACTUALFACTURA")
                        .HasColumnType("bigint");

                    b.Property<int>("Nodigitoscotizacion")
                        .HasColumnName("NODIGITOSCOTIZACION")
                        .HasColumnType("int");

                    b.Property<int>("Nodigitoscreditofiscal")
                        .HasColumnName("NODIGITOSCREDITOFISCAL")
                        .HasColumnType("int");

                    b.Property<int>("Nodigitosfactura")
                        .HasColumnName("NODIGITOSFACTURA")
                        .HasColumnType("int");

                    b.HasKey("Iidconfiguracion")
                        .HasName("PK__CONFIGUR__9203677289C9C782");

                    b.ToTable("CONFIGURACION");
                });

            modelBuilder.Entity("AdminFerreteria.Models.Cotizacion", b =>
                {
                    b.Property<long>("Iidcotizacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IIDCOTIZACION")
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bhabilitado")
                        .HasColumnName("BHABILITADO")
                        .HasColumnType("varchar(1)")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Cotizacionemitida")
                        .HasColumnName("COTIZACIONEMITIDA")
                        .HasColumnType("varchar(2)")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<string>("Cotizacionfacturada")
                        .HasColumnName("COTIZACIONFACTURADA")
                        .HasColumnType("varchar(1)")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<DateTime>("Fechacreacion")
                        .HasColumnName("FECHACREACION")
                        .HasColumnType("date");

                    b.Property<DateTime>("Fechavencimiento")
                        .HasColumnName("FECHAVENCIMIENTO")
                        .HasColumnType("date");

                    b.Property<int>("Iidusuario")
                        .HasColumnName("IIDUSUARIO")
                        .HasColumnType("int");

                    b.Property<string>("Nocotizacion")
                        .IsRequired()
                        .HasColumnName("NOCOTIZACION")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<string>("Nombrecliente")
                        .HasColumnName("NOMBRECLIENTE")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<decimal?>("Total")
                        .HasColumnName("TOTAL")
                        .HasColumnType("decimal(16, 4)");

                    b.HasKey("Iidcotizacion")
                        .HasName("PK__COTIZACI__018E120D0B0F7639");

                    b.HasIndex("Iidusuario");

                    b.ToTable("COTIZACION");
                });

            modelBuilder.Entity("AdminFerreteria.Models.Detallecotizacion", b =>
                {
                    b.Property<long>("Iiddetallecotizacio")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IIDDETALLECOTIZACIO")
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bhabilitado")
                        .HasColumnName("BHABILITADO")
                        .HasColumnType("varchar(1)")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<long>("Cantidad")
                        .HasColumnName("CANTIDAD")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Comision")
                        .HasColumnName("COMISION")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<decimal?>("Descuento")
                        .HasColumnName("DESCUENTO")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<string>("Essubproducto")
                        .IsRequired()
                        .HasColumnName("ESSUBPRODUCTO")
                        .HasColumnType("varchar(2)")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<DateTime>("Fechavencimiento")
                        .HasColumnName("FECHAVENCIMIENTO")
                        .HasColumnType("date");

                    b.Property<long>("Iidcotizacion")
                        .HasColumnName("IIDCOTIZACION")
                        .HasColumnType("bigint");

                    b.Property<long>("Iidproducto")
                        .HasColumnName("IIDPRODUCTO")
                        .HasColumnType("bigint");

                    b.Property<int>("Porcentajecomision")
                        .HasColumnName("PORCENTAJECOMISION")
                        .HasColumnType("int");

                    b.Property<int>("Porcentajedescuento")
                        .HasColumnName("PORCENTAJEDESCUENTO")
                        .HasColumnType("int");

                    b.Property<decimal?>("Precioactual")
                        .HasColumnName("PRECIOACTUAL")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<decimal?>("Subtotal")
                        .HasColumnName("SUBTOTAL")
                        .HasColumnType("decimal(16, 4)");

                    b.HasKey("Iiddetallecotizacio")
                        .HasName("PK__DETALLEC__B66318029EB1D97E");

                    b.HasIndex("Iidcotizacion");

                    b.HasIndex("Iidproducto");

                    b.ToTable("DETALLECOTIZACION");
                });

            modelBuilder.Entity("AdminFerreteria.Models.Detallepedido", b =>
                {
                    b.Property<long>("Iiddetallepedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IIDDETALLEPEDIDO")
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bhabilitado")
                        .IsRequired()
                        .HasColumnName("BHABILITADO")
                        .HasColumnType("varchar(1)")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<long>("Cantidad")
                        .HasColumnName("CANTIDAD")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Comision")
                        .HasColumnName("COMISION")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<decimal?>("Descuento")
                        .HasColumnName("DESCUENTO")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<string>("Essubproducto")
                        .IsRequired()
                        .HasColumnName("ESSUBPRODUCTO")
                        .HasColumnType("varchar(2)")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<DateTime?>("Fechacreacion")
                        .HasColumnName("FECHACREACION")
                        .HasColumnType("date");

                    b.Property<long>("Iidfactura")
                        .HasColumnName("IIDFACTURA")
                        .HasColumnType("bigint");

                    b.Property<long>("Iidproducto")
                        .HasColumnName("IIDPRODUCTO")
                        .HasColumnType("bigint");

                    b.Property<int>("Porcentajecomision")
                        .HasColumnName("PORCENTAJECOMISION")
                        .HasColumnType("int");

                    b.Property<int>("Porcentajedescuento")
                        .HasColumnName("PORCENTAJEDESCUENTO")
                        .HasColumnType("int");

                    b.Property<decimal?>("Precioactual")
                        .HasColumnName("PRECIOACTUAL")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<decimal?>("Subtotal")
                        .HasColumnName("SUBTOTAL")
                        .HasColumnType("decimal(16, 4)");

                    b.HasKey("Iiddetallepedido")
                        .HasName("PK__DETALLEP__6189D32A00E3D89C");

                    b.HasIndex("Iidfactura");

                    b.HasIndex("Iidproducto");

                    b.ToTable("DETALLEPEDIDO");
                });

            modelBuilder.Entity("AdminFerreteria.Models.Empleado", b =>
                {
                    b.Property<int>("Iidempleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IIDEMPLEADO")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bhabilitado")
                        .IsRequired()
                        .HasColumnName("BHABILITADO")
                        .HasColumnType("varchar(1)")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Dui")
                        .IsRequired()
                        .HasColumnName("DUI")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<int>("Edad")
                        .HasColumnName("EDAD")
                        .HasColumnType("int");

                    b.Property<string>("Empleadotieneusuario")
                        .IsRequired()
                        .HasColumnName("EMPLEADOTIENEUSUARIO")
                        .HasColumnType("varchar(1)")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<DateTime?>("Fechacreacion")
                        .HasColumnName("FECHACREACION")
                        .HasColumnType("date");

                    b.Property<string>("Nombrecompleto")
                        .IsRequired()
                        .HasColumnName("NOMBRECOMPLETO")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<int?>("Telefono")
                        .HasColumnName("TELEFONO")
                        .HasColumnType("int");

                    b.HasKey("Iidempleado")
                        .HasName("PK__EMPLEADO__462140DA42AD8C35");

                    b.ToTable("EMPLEADO");
                });

            modelBuilder.Entity("AdminFerreteria.Models.Entrada", b =>
                {
                    b.Property<long>("Iidentrada")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IIDENTRADA")
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bhabilitado")
                        .IsRequired()
                        .HasColumnName("BHABILITADO")
                        .HasColumnType("varchar(1)")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<long>("Cantidad")
                        .HasColumnName("CANTIDAD")
                        .HasColumnType("bigint");

                    b.Property<string>("Condicionventa")
                        .HasColumnName("CONDICIONVENTA")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<long>("Existenciasproducto")
                        .HasColumnName("EXISTENCIASPRODUCTO")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Fechacreacion")
                        .HasColumnName("FECHACREACION")
                        .HasColumnType("date");

                    b.Property<DateTime?>("Fechaexpedicionccf")
                        .HasColumnName("FECHAEXPEDICIONCCF")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("Fechainiciocredito")
                        .HasColumnName("FECHAINICIOCREDITO")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("Fechavencimiento")
                        .HasColumnName("FECHAVENCIMIENTO")
                        .HasColumnType("datetime");

                    b.Property<long>("Iidproducto")
                        .HasColumnName("IIDPRODUCTO")
                        .HasColumnType("bigint");

                    b.Property<string>("Numeroccf")
                        .HasColumnName("NUMEROCCF")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<decimal?>("Preciocompra")
                        .HasColumnName("PRECIOCOMPRA")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<string>("Proveedor")
                        .HasColumnName("PROVEEDOR")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.HasKey("Iidentrada")
                        .HasName("PK__ENTRADA__1AE39997DB223568");

                    b.HasIndex("Iidproducto");

                    b.ToTable("ENTRADA");
                });

            modelBuilder.Entity("AdminFerreteria.Models.Factura", b =>
                {
                    b.Property<long>("Iidfactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IIDFACTURA")
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bhabilitado")
                        .IsRequired()
                        .HasColumnName("BHABILITADO")
                        .HasColumnType("varchar(1)")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<decimal?>("Cambio")
                        .HasColumnName("CAMBIO")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<decimal>("Descuentoglobal")
                        .HasColumnName("DESCUENTOGLOBAL")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<string>("Direccion")
                        .HasColumnName("DIRECCION")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<decimal?>("Efectivo")
                        .HasColumnName("EFECTIVO")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<string>("Facturaemitida")
                        .IsRequired()
                        .HasColumnName("FACTURAEMITIDA")
                        .HasColumnType("varchar(2)")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<DateTime>("Fechacreacion")
                        .HasColumnName("FECHACREACION")
                        .HasColumnType("date");

                    b.Property<string>("Giro")
                        .HasColumnName("GIRO")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<int>("Iidusuario")
                        .HasColumnName("IIDUSUARIO")
                        .HasColumnType("int");

                    b.Property<string>("Nit")
                        .HasColumnName("NIT")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("Nofactura")
                        .IsRequired()
                        .HasColumnName("NOFACTURA")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<string>("Nombrecliente")
                        .IsRequired()
                        .HasColumnName("NOMBRECLIENTE")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<string>("Original")
                        .HasColumnName("ORIGINAL")
                        .HasColumnType("varchar(2)")
                        .HasMaxLength(2)
                        .IsUnicode(false);

                    b.Property<int>("Porcentajedescuentoglobal")
                        .HasColumnName("PORCENTAJEDESCUENTOGLOBAL")
                        .HasColumnType("int");

                    b.Property<string>("Registro")
                        .HasColumnName("REGISTRO")
                        .HasColumnType("varchar(200)")
                        .HasMaxLength(200)
                        .IsUnicode(false);

                    b.Property<string>("Tipocomprador")
                        .IsRequired()
                        .HasColumnName("TIPOCOMPRADOR")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<decimal?>("Total")
                        .HasColumnName("TOTAL")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<decimal>("Totalcomision")
                        .HasColumnName("TOTALCOMISION")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<decimal>("Totaldescuento")
                        .HasColumnName("TOTALDESCUENTO")
                        .HasColumnType("decimal(16, 4)");

                    b.HasKey("Iidfactura")
                        .HasName("PK__FACTURA__C5D90AE94B80389E");

                    b.HasIndex("Iidusuario");

                    b.ToTable("FACTURA");
                });

            modelBuilder.Entity("AdminFerreteria.Models.Inventario", b =>
                {
                    b.Property<long>("Iidinventario")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IIDINVENTARIO")
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bhabilitado")
                        .IsRequired()
                        .HasColumnName("BHABILITADO")
                        .HasColumnType("varchar(1)")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<long>("Cantidad")
                        .HasColumnName("CANTIDAD")
                        .HasColumnType("bigint");

                    b.Property<int>("Iidbodega")
                        .HasColumnName("IIDBODEGA")
                        .HasColumnType("int");

                    b.Property<long>("Iidproducto")
                        .HasColumnName("IIDPRODUCTO")
                        .HasColumnType("bigint");

                    b.Property<int>("Iidstock")
                        .HasColumnName("IIDSTOCK")
                        .HasColumnType("int");

                    b.HasKey("Iidinventario")
                        .HasName("PK__INVENTAR__C5FD6D5CA06FC5DB");

                    b.HasIndex("Iidbodega");

                    b.HasIndex("Iidproducto");

                    b.HasIndex("Iidstock");

                    b.ToTable("INVENTARIO");
                });

            modelBuilder.Entity("AdminFerreteria.Models.Pagina", b =>
                {
                    b.Property<int>("Iidpagina")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IIDPAGINA")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnName("ACCION")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Bhabilitado")
                        .IsRequired()
                        .HasColumnName("BHABILITADO")
                        .HasColumnType("varchar(1)")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Controlador")
                        .IsRequired()
                        .HasColumnName("CONTROLADOR")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<DateTime?>("Fechacreacion")
                        .HasColumnName("FECHACREACION")
                        .HasColumnType("date");

                    b.Property<string>("Icono")
                        .HasColumnName("ICONO")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnName("MENSAJE")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("Iidpagina")
                        .HasName("PK__PAGINA__8E759E4E5CDFE19B");

                    b.ToTable("PAGINA");
                });

            modelBuilder.Entity("AdminFerreteria.Models.Paginatipousuario", b =>
                {
                    b.Property<int>("Iidpaginatipousuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IIDPAGINATIPOUSUARIO")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bhabilitado")
                        .IsRequired()
                        .HasColumnName("BHABILITADO")
                        .HasColumnType("varchar(1)")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<DateTime?>("Fechacreacion")
                        .HasColumnName("FECHACREACION")
                        .HasColumnType("date");

                    b.Property<int>("Iidpagina")
                        .HasColumnName("IIDPAGINA")
                        .HasColumnType("int");

                    b.Property<int>("Iidtipousuario")
                        .HasColumnName("IIDTIPOUSUARIO")
                        .HasColumnType("int");

                    b.HasKey("Iidpaginatipousuario")
                        .HasName("PK__PAGINATI__80FD03168D47A835");

                    b.HasIndex("Iidpagina");

                    b.HasIndex("Iidtipousuario");

                    b.ToTable("PAGINATIPOUSUARIO");
                });

            modelBuilder.Entity("AdminFerreteria.Models.Producto", b =>
                {
                    b.Property<long>("Iidproducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IIDPRODUCTO")
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bhabilitado")
                        .IsRequired()
                        .HasColumnName("BHABILITADO")
                        .HasColumnType("varchar(1)")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Codigoproducto")
                        .IsRequired()
                        .HasColumnName("CODIGOPRODUCTO")
                        .HasColumnType("varchar(15)")
                        .HasMaxLength(15)
                        .IsUnicode(false);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnName("DESCRIPCION")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<decimal?>("Equivalencia")
                        .HasColumnName("EQUIVALENCIA")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<long?>("Existencias")
                        .HasColumnName("EXISTENCIAS")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("Fechacreacion")
                        .HasColumnName("FECHACREACION")
                        .HasColumnType("date");

                    b.Property<decimal?>("Ganancia")
                        .HasColumnName("GANANCIA")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<int>("Iidstock")
                        .HasColumnName("IIDSTOCK")
                        .HasColumnType("int");

                    b.Property<int>("Iidunidadmedida")
                        .HasColumnName("IIDUNIDADMEDIDA")
                        .HasColumnType("int");

                    b.Property<decimal?>("Iva")
                        .HasColumnName("IVA")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<int>("Porcentajeganancia")
                        .HasColumnName("PORCENTAJEGANANCIA")
                        .HasColumnType("int");

                    b.Property<decimal?>("Preciocompra")
                        .HasColumnName("PRECIOCOMPRA")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<decimal?>("Precioventa")
                        .HasColumnName("PRECIOVENTA")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<decimal?>("Restantes")
                        .HasColumnName("RESTANTES")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<decimal?>("Subexistencia")
                        .HasColumnName("SUBEXISTENCIA")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<decimal?>("Subganancia")
                        .HasColumnName("SUBGANANCIA")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<decimal?>("Subiva")
                        .HasColumnName("SUBIVA")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<int?>("Subporcentaje")
                        .HasColumnName("SUBPORCENTAJE")
                        .HasColumnType("int");

                    b.Property<decimal?>("Subpreciounitario")
                        .HasColumnName("SUBPRECIOUNITARIO")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<decimal?>("Subprecioventa")
                        .HasColumnName("SUBPRECIOVENTA")
                        .HasColumnType("decimal(16, 4)");

                    b.Property<int?>("Subunidad")
                        .HasColumnName("SUBUNIDAD")
                        .HasColumnType("int");

                    b.HasKey("Iidproducto")
                        .HasName("PK__PRODUCTO__158EDF304C3F3F3B");

                    b.HasIndex("Iidstock");

                    b.HasIndex("Iidunidadmedida");

                    b.ToTable("PRODUCTO");
                });

            modelBuilder.Entity("AdminFerreteria.Models.Stock", b =>
                {
                    b.Property<int>("Iidstock")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IIDSTOCK")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bhabilitado")
                        .IsRequired()
                        .HasColumnName("BHABILITADO")
                        .HasColumnType("varchar(1)")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<DateTime>("Fechacreacion")
                        .HasColumnName("FECHACREACION")
                        .HasColumnType("date");

                    b.Property<string>("Nombrestock")
                        .IsRequired()
                        .HasColumnName("NOMBRESTOCK")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("Iidstock")
                        .HasName("PK__STOCK__5EBABD9FE67EDAB3");

                    b.ToTable("STOCK");
                });

            modelBuilder.Entity("AdminFerreteria.Models.Tipousuario", b =>
                {
                    b.Property<int>("Iidtipousuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IIDTIPOUSUARIO")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bhabilitado")
                        .IsRequired()
                        .HasColumnName("BHABILITADO")
                        .HasColumnType("varchar(1)")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnName("DESCRIPCION")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<DateTime?>("Fechacreacion")
                        .HasColumnName("FECHACREACION")
                        .HasColumnType("date");

                    b.Property<string>("Nombretipousuario")
                        .IsRequired()
                        .HasColumnName("NOMBRETIPOUSUARIO")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("Iidtipousuario")
                        .HasName("PK__TIPOUSUA__A05A9116419E2F34");

                    b.ToTable("TIPOUSUARIO");
                });

            modelBuilder.Entity("AdminFerreteria.Models.Unidadmedida", b =>
                {
                    b.Property<int>("Iidunidadmedida")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IIDUNIDADMEDIDA")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bhabilitado")
                        .IsRequired()
                        .HasColumnName("BHABILITADO")
                        .HasColumnType("varchar(1)")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<DateTime?>("Fechacreacion")
                        .HasColumnName("FECHACREACION")
                        .HasColumnType("date");

                    b.Property<string>("Nombreunidad")
                        .IsRequired()
                        .HasColumnName("NOMBREUNIDAD")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.HasKey("Iidunidadmedida")
                        .HasName("PK__UNIDADME__D8851CA5DF24E311");

                    b.ToTable("UNIDADMEDIDA");
                });

            modelBuilder.Entity("AdminFerreteria.Models.Usuario", b =>
                {
                    b.Property<int>("Iidusuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IIDUSUARIO")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bhabilitado")
                        .IsRequired()
                        .HasColumnName("BHABILITADO")
                        .HasColumnType("varchar(1)")
                        .HasMaxLength(1)
                        .IsUnicode(false);

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnName("CONTRASEÑA")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<DateTime?>("Fechacreacion")
                        .HasColumnName("FECHACREACION")
                        .HasColumnType("date");

                    b.Property<int>("Iidempleado")
                        .HasColumnName("IIDEMPLEADO")
                        .HasColumnType("int");

                    b.Property<int>("Iidtipousuario")
                        .HasColumnName("IIDTIPOUSUARIO")
                        .HasColumnType("int");

                    b.Property<string>("Nombreusuario")
                        .IsRequired()
                        .HasColumnName("NOMBREUSUARIO")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.HasKey("Iidusuario")
                        .HasName("PK__USUARIO__26DBFF593A56E8F3");

                    b.HasIndex("Iidempleado");

                    b.HasIndex("Iidtipousuario");

                    b.ToTable("USUARIO");
                });

            modelBuilder.Entity("AdminFerreteria.Models.Bitacoraentrada", b =>
                {
                    b.HasOne("AdminFerreteria.Models.Entrada", "IidentradaNavigation")
                        .WithMany("Bitacoraentrada")
                        .HasForeignKey("Iidentrada")
                        .HasConstraintName("FK__BITACORAE__IIDEN__4F47C5E3")
                        .IsRequired();
                });

            modelBuilder.Entity("AdminFerreteria.Models.Bitacorasistema", b =>
                {
                    b.HasOne("AdminFerreteria.Models.Usuario", "IidusuarioNavigation")
                        .WithMany("Bitacorasistema")
                        .HasForeignKey("Iidusuario")
                        .HasConstraintName("FK__BITACORAS__IIDUS__7E37BEF6")
                        .IsRequired();
                });

            modelBuilder.Entity("AdminFerreteria.Models.Cotizacion", b =>
                {
                    b.HasOne("AdminFerreteria.Models.Usuario", "IidusuarioNavigation")
                        .WithMany("Cotizacion")
                        .HasForeignKey("Iidusuario")
                        .HasConstraintName("FK__COTIZACIO__IIDUS__6E01572D")
                        .IsRequired();
                });

            modelBuilder.Entity("AdminFerreteria.Models.Detallecotizacion", b =>
                {
                    b.HasOne("AdminFerreteria.Models.Cotizacion", "IidcotizacionNavigation")
                        .WithMany("Detallecotizacion")
                        .HasForeignKey("Iidcotizacion")
                        .HasConstraintName("FK__DETALLECO__IIDCO__5EBF139D")
                        .IsRequired();

                    b.HasOne("AdminFerreteria.Models.Producto", "IidproductoNavigation")
                        .WithMany("Detallecotizacion")
                        .HasForeignKey("Iidproducto")
                        .HasConstraintName("FK__DETALLECO__IIDPR__5FB337D6")
                        .IsRequired();
                });

            modelBuilder.Entity("AdminFerreteria.Models.Detallepedido", b =>
                {
                    b.HasOne("AdminFerreteria.Models.Factura", "IidfacturaNavigation")
                        .WithMany("Detallepedido")
                        .HasForeignKey("Iidfactura")
                        .HasConstraintName("FK__DETALLEPE__IIDFA__5165187F")
                        .IsRequired();

                    b.HasOne("AdminFerreteria.Models.Producto", "IidproductoNavigation")
                        .WithMany("Detallepedido")
                        .HasForeignKey("Iidproducto")
                        .HasConstraintName("FK__DETALLEPE__IIDPR__52593CB8")
                        .IsRequired();
                });

            modelBuilder.Entity("AdminFerreteria.Models.Entrada", b =>
                {
                    b.HasOne("AdminFerreteria.Models.Producto", "IidproductoNavigation")
                        .WithMany("Entrada")
                        .HasForeignKey("Iidproducto")
                        .HasConstraintName("FK__ENTRADA__IIDPROD__3E52440B")
                        .IsRequired();
                });

            modelBuilder.Entity("AdminFerreteria.Models.Factura", b =>
                {
                    b.HasOne("AdminFerreteria.Models.Usuario", "IidusuarioNavigation")
                        .WithMany("Factura")
                        .HasForeignKey("Iidusuario")
                        .HasConstraintName("FK__FACTURA__IIDUSUA__4E88ABD4")
                        .IsRequired();
                });

            modelBuilder.Entity("AdminFerreteria.Models.Inventario", b =>
                {
                    b.HasOne("AdminFerreteria.Models.Bodega", "IidbodegaNavigation")
                        .WithMany("Inventario")
                        .HasForeignKey("Iidbodega")
                        .HasConstraintName("FK__INVENTARI__IIDBO__2B0A656D")
                        .IsRequired();

                    b.HasOne("AdminFerreteria.Models.Producto", "IidproductoNavigation")
                        .WithMany("Inventario")
                        .HasForeignKey("Iidproducto")
                        .HasConstraintName("FK__INVENTARI__IIDPR__2BFE89A6")
                        .IsRequired();

                    b.HasOne("AdminFerreteria.Models.Stock", "IidstockNavigation")
                        .WithMany("Inventario")
                        .HasForeignKey("Iidstock")
                        .HasConstraintName("FK__INVENTARI__IIDST__3A4CA8FD")
                        .IsRequired();
                });

            modelBuilder.Entity("AdminFerreteria.Models.Paginatipousuario", b =>
                {
                    b.HasOne("AdminFerreteria.Models.Pagina", "IidpaginaNavigation")
                        .WithMany("Paginatipousuario")
                        .HasForeignKey("Iidpagina")
                        .HasConstraintName("FK__PAGINATIP__IIDPA__4AB81AF0")
                        .IsRequired();

                    b.HasOne("AdminFerreteria.Models.Tipousuario", "IidtipousuarioNavigation")
                        .WithMany("Paginatipousuario")
                        .HasForeignKey("Iidtipousuario")
                        .HasConstraintName("FK__PAGINATIP__IIDTI__4BAC3F29")
                        .IsRequired();
                });

            modelBuilder.Entity("AdminFerreteria.Models.Producto", b =>
                {
                    b.HasOne("AdminFerreteria.Models.Stock", "IidstockNavigation")
                        .WithMany("Producto")
                        .HasForeignKey("Iidstock")
                        .HasConstraintName("FK__PRODUCTO__IIDSTO__160F4887")
                        .IsRequired();

                    b.HasOne("AdminFerreteria.Models.Unidadmedida", "IidunidadmedidaNavigation")
                        .WithMany("Producto")
                        .HasForeignKey("Iidunidadmedida")
                        .HasConstraintName("FK__PRODUCTO__IIDUNI__398D8EEE")
                        .IsRequired();
                });

            modelBuilder.Entity("AdminFerreteria.Models.Usuario", b =>
                {
                    b.HasOne("AdminFerreteria.Models.Empleado", "IidempleadoNavigation")
                        .WithMany("Usuario")
                        .HasForeignKey("Iidempleado")
                        .HasConstraintName("FK__USUARIO__IIDEMPL__44FF419A")
                        .IsRequired();

                    b.HasOne("AdminFerreteria.Models.Tipousuario", "IidtipousuarioNavigation")
                        .WithMany("Usuario")
                        .HasForeignKey("Iidtipousuario")
                        .HasConstraintName("FK__USUARIO__IIDTIPO__45F365D3")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
