create procedure sp_crear_paginas_sistema
as
begin
	SET IDENTITY_INSERT [dbo].[PAGINA] ON 
	INSERT [dbo].[PAGINA] ([IIDPAGINA], [MENSAJE], [ACCION], [CONTROLADOR], [FECHACREACION], [BHABILITADO], [ICONO]) VALUES (1, N'PERMISOS', N'INDEX', N'TIPOUSUARIO', CAST(N'1901-05-21' AS Date), N'A', N'fas fa-shield-alt')
	INSERT [dbo].[PAGINA] ([IIDPAGINA], [MENSAJE], [ACCION], [CONTROLADOR], [FECHACREACION], [BHABILITADO], [ICONO]) VALUES (2, N'EMPLEADOS', N'INDEX', N'EMPLEADO', CAST(N'1901-05-21' AS Date), N'A', N'fas fa-users')
	INSERT [dbo].[PAGINA] ([IIDPAGINA], [MENSAJE], [ACCION], [CONTROLADOR], [FECHACREACION], [BHABILITADO], [ICONO]) VALUES (3, N'STOCK', N'INDEX', N'STOCK', CAST(N'1901-05-21' AS Date), N'A', N'fas fa-dolly')
	INSERT [dbo].[PAGINA] ([IIDPAGINA], [MENSAJE], [ACCION], [CONTROLADOR], [FECHACREACION], [BHABILITADO], [ICONO]) VALUES (4, N'UNIDAD DE MEDIDA', N'INDEX', N'UNIDADMEDIDA', CAST(N'1901-05-21' AS Date), N'A', N'fas fa-ruler-vertical')
	INSERT [dbo].[PAGINA] ([IIDPAGINA], [MENSAJE], [ACCION], [CONTROLADOR], [FECHACREACION], [BHABILITADO], [ICONO]) VALUES (5, N'PRODUCTOS', N'INDEX', N'PRODUCTO', CAST(N'1901-05-21' AS Date), N'A', N'fas fa-boxes')
	INSERT [dbo].[PAGINA] ([IIDPAGINA], [MENSAJE], [ACCION], [CONTROLADOR], [FECHACREACION], [BHABILITADO], [ICONO]) VALUES (6, N'ENTRADAS', N'INDEX', N'ENTRADA', CAST(N'1901-05-21' AS Date), N'A', N'fas fa-box-open')
	INSERT [dbo].[PAGINA] ([IIDPAGINA], [MENSAJE], [ACCION], [CONTROLADOR], [FECHACREACION], [BHABILITADO], [ICONO]) VALUES (7, N'EXISTENCIA BAJA', N'INDEX', N'EXISTENCIA', CAST(N'1901-05-21' AS Date), N'A', N'fas fa-exclamation-triangle')
	INSERT [dbo].[PAGINA] ([IIDPAGINA], [MENSAJE], [ACCION], [CONTROLADOR], [FECHACREACION], [BHABILITADO], [ICONO]) VALUES (8, N'BODEGA E INVENTARIO', N'INDEX', N'BODEGAINVENTARIO', CAST(N'1901-05-21' AS Date), N'A', N'fas fa-laptop-house')
	INSERT [dbo].[PAGINA] ([IIDPAGINA], [MENSAJE], [ACCION], [CONTROLADOR], [FECHACREACION], [BHABILITADO], [ICONO]) VALUES (9, N'VENDER', N'INDEX', N'VENTA', CAST(N'1901-05-21' AS Date), N'A', N'fas fa-money-check-alt')
	INSERT [dbo].[PAGINA] ([IIDPAGINA], [MENSAJE], [ACCION], [CONTROLADOR], [FECHACREACION], [BHABILITADO], [ICONO]) VALUES (10, N'COTIZAR', N'INDEX', N'COTIZACION', CAST(N'2020-10-10' AS Date), N'A', N'fas fa-list-alt')
	INSERT [dbo].[PAGINA] ([IIDPAGINA], [MENSAJE], [ACCION], [CONTROLADOR], [FECHACREACION], [BHABILITADO], [ICONO]) VALUES (11, N'FACTURAR COTIZACION', N'INDEX', N'COTIZACIONPENDIENTE', CAST(N'2020-10-10' AS Date), N'A', N'fas fa-clock')
	INSERT [dbo].[PAGINA] ([IIDPAGINA], [MENSAJE], [ACCION], [CONTROLADOR], [FECHACREACION], [BHABILITADO], [ICONO]) VALUES (12, N'CAJA', N'INDEX', N'FACTURA', CAST(N'2020-10-10' AS Date), N'A', N'fas fa-cash-register')
	INSERT [dbo].[PAGINA] ([IIDPAGINA], [MENSAJE], [ACCION], [CONTROLADOR], [FECHACREACION], [BHABILITADO], [ICONO]) VALUES (13, N'FACTURAS EMITIDAS', N'INDEX', N'FACTURAEMITIDA', CAST(N'2020-10-10' AS Date), N'A', N'fas fa-folder-open')
	INSERT [dbo].[PAGINA] ([IIDPAGINA], [MENSAJE], [ACCION], [CONTROLADOR], [FECHACREACION], [BHABILITADO], [ICONO]) VALUES (15, N'REPORTE DE VENTAS', N'INDEX', N'REPORTE', CAST(N'2020-10-10' AS Date), N'A', N'fas fa-file-pdf')
	INSERT [dbo].[PAGINA] ([IIDPAGINA], [MENSAJE], [ACCION], [CONTROLADOR], [FECHACREACION], [BHABILITADO], [ICONO]) VALUES (17, N'COMPRADOR FISCAL', N'INDEX', N'CLIENTE', CAST(N'2020-12-04' AS Date), N'A', N'fas fa-users')
	INSERT [dbo].[PAGINA] ([IIDPAGINA], [MENSAJE], [ACCION], [CONTROLADOR], [FECHACREACION], [BHABILITADO], [ICONO]) VALUES (18, N'BITACORA DE SISTEMA', N'INDEX', N'BITACORASISTEMA', CAST(N'2020-12-04' AS Date), N'A', N'fas fa-list')
	INSERT [dbo].[PAGINA] ([IIDPAGINA], [MENSAJE], [ACCION], [CONTROLADOR], [FECHACREACION], [BHABILITADO], [ICONO]) VALUES (19, N'CONFIGURACIONES', N'INDEX', N'CONFIGURACION', CAST(N'2020-12-04' AS Date), N'A', N'fas fa-cogs')
	SET IDENTITY_INSERT [dbo].[PAGINA] OFF
end